wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1682754526.559465
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.13
      5: 0.13.9
      8:
      - 1
      - 5
