name: Unit and Smoke Tests using conda env
on:
    pull_request:
        paths:
            - test-example/**
    workflow_dispatch:

defaults:
    run:
        shell: bash -el {0}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Copy Repository Content
                uses: actions/checkout@main
            
            -   name: Install conda using microMamba
                uses: mamba-org/provision-with-micromamba@main
                with:
                    environment-file: test-example/conda-environment.yaml
                    environment-name: course
                    cache-env: true
                    cache-downloads: true

            -   name: Install pytest
                run: |
                    micromamba activate course
                    pip install -U pytest
                    pytest test-example/
                env:
                    WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

