name: trigger-demo
run-name: ${{github.actor}} is testing out Github Actions
on: 
    push:
        branches:
            - main
    pull_request:

jobs:
    trigger-demo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "first pull request tigger github action"
    